title = "NATAN"
theme = 'digitalgarden'
languageCode = 'de-DE'

baseURL = "/"
googleAnalytics = "UA-PROPERTY_ID"

[Params]
  description = "Initiative NATAN"
  images = ['/digital-garden-logo.png']
  enableSearch = true

[menu]
[[menu.main]]
  name = 'Eingangsseite'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Süddeutschland'
  params.header = true
  weight = 2
[[menu.main]]
  name = 'Synagogen'
  url = '/synagogen'
  weight = 3
[[menu.main]]
  name = 'Friedhöfe'
  url = '/friedhoefe'
  weight = 4
[[menu.main]]
  name = 'Museen'
  url = '/museen'
  weight = 5
[[menu.main]]
  name = 'Kontakt'
  url = '/kontakt'
  weight = 6

[[menu.main]]
  name = 'Gesellschaft'
  params.header = true
  weight = 7
[[menu.main]]
  name = 'Sport'
  url = '/sport'
  weight = 8
[[menu.main]]
  name = 'Initiativen'
  url = '/initiativen'
  weight = 9
[[menu.main]]
  name = 'Antisemitismus'
  url = '/anti'
  weight = 10
[[menu.main]]
  name = 'Kultur'
  url = '/kultur'
  weight = 11
[[menu.main]]
  name = 'Im Portrait'
  url = '/portrait'
  weight = 12

[[menu.main]]
  name = 'Links'
  params.header = true
  weight = 13
[[menu.main]]
  name = 'Rechtliches'
  url = '/rechtliches'
  weight = 14

[Params.newsletter]
  title = ""
  description = "Eine kuratierte wöchentliche Übersicht einmal pro Woche in Ihrem Postfach"

  # Supports buttondown, substack and revue
  provider = "buttondown"

  # Buttondown - URL from share page; Refer: https://blog.buttondown.email/2019/10/11/adding-a-buttondown-subscription-form-to-webflow#getting-your-subscription-url
  # Substack - URL of the newsletter homepage; Example: https://on.substack.com/
  # Revue - Username
  path = "https://buttondown.email/api/emails/embed-subscribe/"


# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
